# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d26d68268a4b2760d187cfd50a2ac5cbd0585fbfdbe944e8309d11367b7b5c1f4e1c5fa0c73c7f147e7265c12b317fca29b7869e654f331a8a79beb141c414

test:
  secret_key_base: 90b410d27b2f1d295014f3c3eaee243cdf85227e1be1400b6c148dbfa489d30561ef271e2d2ca4a640c6d011666fce4fef1f631c70d8c8aca735839ac10b898f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
